<a href="https://colab.research.google.com/github/zxcusa/DA-Pandas/blob/main/D_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    'mahsulot' : ['Non','Sut','Daftar','Ruchka','Guruch'],
    'kategoriya' : ['Oziq-ovqat','Oziq-ovqat','Kantseleriya','Oziq-ovqat','Oziq-ovqat'],
    'narx' : [4500, 12000, 8000, 3000, 18000],
    'soni' : [120, 45, 60, 200, 30],
    'shahar' : ['Toshkent','Buxoro','Samarqand','Xorazm',"Xiva"]
}

In [ ]:
df=pd.DataFrame(data)
df.sample(5)

  mahsulot    kategoriya   narx  soni     shahar
0      Non    Oziq-ovqat   4500   120   Toshkent
4   Guruch    Oziq-ovqat  18000    30       Xiva
1      Sut    Oziq-ovqat  12000    45     Buxoro
2   Daftar  Kantseleriya   8000    60  Samarqand
3   Ruchka    Oziq-ovqat   3000   200     Xorazm

In [ ]:
df = df.set_index('mahsulot')

In [ ]:
df.loc['Sut']

kategoriya    Oziq-ovqat
narx               12000
soni                  45
shahar            Buxoro
Name: Sut, dtype: object

In [ ]:
df.loc['Sut', 'narx']

np.int64(12000)

In [ ]:
df.loc[['Non', 'Sut']]

          kategoriya   narx  soni    shahar
mahsulot
Non       Oziq-ovqat   4500   120  Toshkent
Sut       Oziq-ovqat  12000    45    Buxoro

In [ ]:
df.loc['Non':'Daftar']

            kategoriya   narx  soni     shahar
mahsulot
Non         Oziq-ovqat   4500   120   Toshkent
Sut         Oziq-ovqat  12000    45     Buxoro
Daftar    Kantseleriya   8000    60  Samarqand

In [ ]:
df.loc[:, 'narx']

mahsulot
Non        4500
Sut       12000
Daftar     8000
Ruchka     3000
Guruch    18000
Name: narx, dtype: int64

In [ ]:
df.loc['Non':'Sut', ['narx', 'soni']]

           narx  soni
mahsulot
Non        4500   120
Sut       12000    45

In [ ]:
df = df.rename(columns={'narx': 'narx_som',
'soni': 'miqdor'})

In [ ]:
df = df.rename(index={0: 'birinchi'})

In [ ]:
df=pd.DataFrame(data)
df.sample(5)

  mahsulot    kategoriya   narx  soni     shahar
4   Guruch    Oziq-ovqat  18000    30       Xiva
2   Daftar  Kantseleriya   8000    60  Samarqand
1      Sut    Oziq-ovqat  12000    45     Buxoro
3   Ruchka    Oziq-ovqat   3000   200     Xorazm
0      Non    Oziq-ovqat   4500   120   Toshkent

In [ ]:
df.iloc[[1,4]],[[1,3]]

(  mahsulot  kategoriya   narx  soni  shahar
 1      Sut  Oziq-ovqat  12000    45  Buxoro
 4   Guruch  Oziq-ovqat  18000    30    Xiva,
 [[1, 3]])

In [ ]:
df[df['soni']<80]

  mahsulot    kategoriya   narx  soni     shahar
1      Sut    Oziq-ovqat  12000    45     Buxoro
2   Daftar  Kantseleriya   8000    60  Samarqand
4   Guruch    Oziq-ovqat  18000    30       Xiva

In [ ]:
df[(df['narx'] > 5000) & (df['soni'] < 100)]

  mahsulot    kategoriya   narx  soni     shahar
1      Sut    Oziq-ovqat  12000    45     Buxoro
2   Daftar  Kantseleriya   8000    60  Samarqand
4   Guruch    Oziq-ovqat  18000    30       Xiva

In [ ]:
df.drop(columns=['narx'])

  mahsulot    kategoriya  soni     shahar
0      Non    Oziq-ovqat   120   Toshkent
1      Sut    Oziq-ovqat    45     Buxoro
2   Daftar  Kantseleriya    60  Samarqand
3   Ruchka    Oziq-ovqat   200     Xorazm
4   Guruch    Oziq-ovqat    30       Xiva